# traefik默认使用host network
# 在Unix系统上, 绑定到小于1024的端口通常需要超级用户权限: 1. 使用CAP_NET_BIND_SERVICE; 2. runAsUser: 0; 3. 使用hostwork
hostNetwork: true
ports:
  web:
    port: 80
    hostPort: 80
  websecure:
    port: 443
    hostPort: 443
  traefik:
    port: 9000

service:
  enabled: false

logs:
  general:
    level: DEBUG
  access:
    enabled: true

additionalArguments: 
- "--api=true"
- "--api.insecure=true"
- "--api.dashboard=true"

ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.yanggq.com`) &&(PathPrefix(`/dashboard`) || PathPrefix(`/api`))
    entryPoints: ["web"]