# traefik默认使用host network
hostNetwork: false
ports:
  web:
    port: 80
    expose: false
    hostPort: 80
  websecure:
    port: 443
    expose: false
    hostPort: 443
  traefik:
    port: 9000
    expose: true
service:
  enabled: false

logs:
  general:
    level: DEBUG
  access:
    enabled: true

additionalArguments: 
- "--api=true"
- "--api.insecure=true"
- "--api.dashboard=true"

ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.yanggq.com`) &&(PathPrefix(`/dashboard`) || PathPrefix(`/api`))
    entryPoints: ["web"]