# 不创建dashboard ingressRoute
ingressRoute:
  dashboard:
    enabled: false
    
hostNetwork: true
# 使用宿主机上的端口暴露端点, 不需要创建k8s service; 同时确保hostNetwork=true, 并且容器端口和宿主机端口保持一致
ports:
  web:
    port: 80
    hostPort: 80
  websecure:
    port: 443
    hostPort: 443
service:
  enabled: false

logs:
  general:
    level: DEBUG
  access:
    enabled: true

# 调度到master节点, 设置污点容忍
nodeSelector:
  "traefik": "true"
tolerations:
- key: "node-role.kubernetes.io/control-plane"
  operator: "Exists"
  effect: "NoSchedule"

