# traefik默认使用host network
hostNetwork: false
ports:
  web:
    port: 8000
    expose: true
    exposedPort: 80
    nodePort: 31004
  websecure:
    port: 8443
    expose: true
    exposedPort: 443
    nodePort: 31005
  traefik:
    port: 9000
    expose: true
    exposedPort: 9000
    nodePort: 31006
service:
  enabled: true
  type: NodePort

logs:
  general:
    level: DEBUG
  access:
    enabled: true

additionalArguments: 
- "--api=true"
- "--api.insecure=true"
- "--api.dashboard=true"

ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.yanggq.com`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
    entryPoints: ["web"]


