api:
  dashboard: true
  insecure: true
  debug: true
  
# 创建dashboard ingressRoute
ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.yanggq.com`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
    entryPoints: ["web"]

# 使用宿主机上的端口暴露端点, 不需要创建k8s service; 同时确保hostNetwork=true, 并且容器端口和宿主机端口保持一致
ports:
  web:
    port: 80
    nodePort: 31005
  websecure:
    port: 443
    nodePort: 31006
  traefik:
    port: 8080
    nodePort: 31007
service:
  enabled: true

logs:
  general:
    level: DEBUG
  access:
    enabled: true

# 调度到master节点, 设置污点容忍
nodeSelector:
  "traefik": "true"
tolerations:
- key: "node-role.kubernetes.io/control-plane"
  operator: "Exists"
  effect: "NoSchedule"

deployment:
  enabled: true
  kind: Deployment
  replicas: 1

metrics:
  prometheus:
    addEntryPointsLabels: false
